data:
  num_nodes: 5183
  input_window: 12
  output_window: 12
  output_dim: 1
  normalizer: tec01
model:
  name: GWN
train:
  epochs: 1
  batch_size: 192
  amp: true
  optimizer: adam
  scheduler: none
  lr_init: 0.001
  weight_decay: 0.0
  early_stop: true
  early_stop_patience: 20
  accumulate_steps: 2
  log_step: 50
  year_split: true
physics:
  use_pinn: true
  lambda_phys: 0.2
  use_diffusion: true
  use_drivers: true
  use_adv: true
  nochem: false
init:
  init_from: "/root/tecGPT/Output/GIMtec/pretrain/20250913_235301_GIMtec_gptst_pretrain_GWN_grid8.pth"
